# Generated by Django 2.0.1 on 2018-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=100)),
                ('lunch', models.CharField(max_length=100)),
                ('dinner', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cardio', models.CharField(max_length=100)),
            ],
        ),
    ]
